services:
  shape_rest:
    image: card_rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    develop:
      watch:
        - action: rebuild
          path: .
          target: /cardrest
